[workspace]
resolver = "2"
members = ["make-snapshot", "generate-grub", "utils"]

[workspace.dependencies]
chrono = "0.4"
miette = { version = "7.5", features = ["fancy"] }
anstyle = "1.0"
upon = "0.10"
