[package]
name = "generate-grub"
version = "0.1.0"
edition = "2024"

[dependencies]
miette = { workspace = true }
anstyle = { workspace = true }
upon = { workspace = true }
utils = { path = "../utils" }
